let inventory=[];
const max_carried = 17;
const sleep_time=5000;

let game = {
    apple_given: false,
    cabinet_open: false,
    called_555_0439: false,
    called_555_0987: false,
    called_555_6969: false,
    candy_given: false,
    cash: 1000,
    closet_open: false,
    doll_inflated: false,
    door_W_open: false,
    drawer_open: false,
    flowers_given: false,
    girl_2_fucked: false,
    hole_peeped: false,
    hooker_fucked: false,
    married_to_girl: false,
    objects_carried: [],
    pitcher_full: false,
    radio_listened: false,
    ring_given: false,
    rope_in_use: false,
    rubber_worn: false,
    rubber_lubricated: '',
    rubber_ribbed: '',
    rubber_color: '',
    rubber_flavor: '',
    score: 0,
    seeds_planted: false,
    seeds_watered: false,
    stool_climbed: false,
    telephone_answered: false,
    telephone_ringing: false,
    tied_to_bed: false,
    toilet_flushed: false,
    TV_channel: 0,
    water_on: false,
    window_broken: false,
    wine_ordered: false,
    your_place: "b_bar",
    girl_location: "c_hmoons",
};

var girl_name='';
var girl_do='';
var your_part='';
var your_object='';
var girl_part='';

const verbs = 
[
    "break",
    "buy",
    "bye",
    "climb",
    "close",
    "d","down",
    "dance",
    "drink",
    "drop",
    "e", "east",
    "eat",
    "enter",
    "examine",
    "fill",
    "fuck",
    "get",
    "give",
    "go",
    "grab",
    "help",
    "inflate",
    "jump",
    "kiss",
    "leave",
    "listen",
    "look",
    "n", "north",
    "open",
    "order",
    "plant",
    "play",
    "pour",
    "press", "push",
    "pull",
    "quit",
    "read",
    "restore",
    "s", "south",
    "save",
    "score",
    "search",
    "smash",
    "smell",
    "smoke",
    "stab",
    "stop",
    "take",
    "u", "up",
    "use",
    "w", "west",
    "watch",
    "water",
    "wear"
];