let inventory=[];
const max_carried = 17;
const sleep_time=5000;

let game = {
your_place: "b_bar",
objects_carried: 0,
TV_channel: 0,
cash: 1000,
score: 0,
rope_in_use: false,
window_broken: false,
toilet_flushed: false,
called_555_0987: false,
called_555_6969: false,
called_555_0439: false,
rubber_worn: false,
hooker_fucked: false,
door_W_open: false,
radio_listened: false,
wine_ordered: false,
telephone_ringing: false,
telephone_answered: false,
hole_peeped: false,
girl_2_fucked: false,
tied_to_bed: false,
drawer_open: false,
closet_open: false,
cabinet_open: false,
doll_inflated: false,
stool_climbed: false,
water_on: false,
pitcher_full: false,
seeds_planted: false,
seeds_watered: false,
apple_given: false,
candy_given: false,
flowers_given: false,
ring_given: false,
married_to_girl: false
};