let inventory=[];
let your_place;
let new_place;
let cash;
let max_carried;
let objects_carried ;
let TV_channel;
let money;
let score;
let rope_in_use = false;
let window_broken = false;
let toilet_flushed = false;
let called_555_0987 = false;
let called_555_6969 = false;
let called_555_0439 = false;
let rubber_worn = false;
let hooker_fucked = false;
let door_W_open = false;
let radio_listened = false;
let wine_ordered = false;
let telephone_ringing = false;
let telephone_answered = false;
let hole_peeped = false;
let girl_2_fucked = false;
let tied_to_bed = false;
let drawer_open = false;
let closet_open = false;
let cabinet_open = false;
let doll_inflated = false;
let stool_climbed = false;
let water_on = false;
let pitcher_full = false;
let seeds_planted = false;
let seeds_watered = false;
let apple_given = false;
let candy_given = false;
let flowers_given = false;
let ring_given = false;
let married_to_girl = false;

